services:
  - type: web
    name: quiz-system-backend
    runtime: python
    buildCommand: pip install -r requirements.txt && python manage.py migrate
    startCommand: gunicorn config.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: DEBUG
        value: False
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: .onrender.com,quiz-system-78263.web.app
      - key: DATABASE_URL
        fromDatabase:
          name: quiz-db
          property: connectionString
      - key: FRONTEND_URL
        value: https://quiz-system-78263.web.app
      - key: EMAIL_BACKEND
        value: django.core.mail.backends.console.EmailBackend

databases:
  - name: quiz-db
    plan: free
